version: '3'
services:
  web:
    container_name: webapp-frontend
    build: .
    ports:
      - "5000:5000"
    environment:
      - noddy=nobody
  redis:
    container_name: redis-backend
    image: "redis:alpine"
    environment:
      - Bob=bobo
